"use strict";
var stack_1 = require("./stack");
var queue_1 = require("./queue");
var st = new stack_1.default();
st.push(1);
st.push(2);
st.push(3);
st.push(4);
console.log(st.pop());
console.log(st.pop());
console.log(st.pop());
console.log(st.pop());
var cue = new queue_1.default();
cue.queue(1);
cue.queue(2);
cue.queue(3);
cue.queue(4);
cue.queue(5);
cue.queue(6);
console.log(cue.dequeue());
console.log(cue.dequeue());
console.log(cue.dequeue());
cue.queue(7);
console.log(cue.dequeue());
cue.queue(8);
console.log(cue.dequeue());
console.log(cue.dequeue());
console.log(cue.dequeue());
console.log(cue.dequeue());
