"use strict";
var linkedList_1 = require("./linkedList");
var stack_1 = require("./stack");
var st = new stack_1.default();
var ll = new linkedList_1.default();
st.push(1);
st.push(2);
st.push(3);
st.push(4);
console.log(st.pop());
console.log(st.pop());
console.log(st.pop());
console.log(st.pop());
